#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the "beautify" task
echo "🤞🏻 We are checking lint and typescript..."

lerna run --concurrency 1 --stream pre-commit --since HEAD --exclude-dependents 

echo "✅ Passed lint"