#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n================================================================"
echo "🤞🏻 We are checking lint and typescript..."
echo "================================================================"

lerna run --concurrency 1 --stream pre-commit --since HEAD --exclude-dependents 

echo "================================================================"
echo "✅ Yeah, lint and typscript are passed ✅"
echo "================================================================"